FROM centos
RUN yum install -y vim wget
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN sh ./Miniconda3-latest-Linux-x86_64.sh -b
RUN /root/minconda3/bin/conda init
